---
- name: Configure master to use etcd3 storage backend
  yedit:
    src: /etc/origin/master/master-config.yaml
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: kubernetesMasterConfig.apiServerArguments.storage-backend
      value:
        - etcd3
    - key: kubernetesMasterConfig.apiServerArguments.storage-media-type
      value:
        - application/vnd.kubernetes.protobuf
