---
- include: ../../init/evaluate_groups.yml

- name: Ensure there are new_nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - fail:
      msg: >
        Detected no new_nodes in inventory. Please add hosts to the
        new_nodes host group to add nodes.
    when:
    - g_new_node_hosts | default([]) | length == 0

# Need a better way to do the above check for node without
# running evaluate_groups and init/main.yml
- include: ../../init/main.yml

- include: ../../common/openshift-node/config.yml
