---
- fail: msg="Currently, NetworkManager must be installed and enabled prior to installation."
  when: not openshift_node_bootstrap | bool

- name: Install NetworkManager during node_bootstrap provisioning
  package:
    name: NetworkManager
    state: present
  notify: restart NetworkManager

- include: ./network-manager.yml
