---
- name: Node Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Node install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_node:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- include: certificates.yml

- include: setup.yml

- include: containerized_nodes.yml

- include: configure_nodes.yml

- include: additional_config.yml

- include: manage_node.yml

- include: enable_excluders.yml

- name: Node Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Node install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_node:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
