---
- name: normalize groups
  include: ../../init/evaluate_groups.yml

- name: initialize the facts
  include: ../../init/facts.yml

- name: initialize the repositories
  include: ../../init/repos.yml

- name: run node config setup
  include: setup.yml

- name: run node config
  include: configure_nodes.yml

- name: Re-enable excluders
  include: enable_excluders.yml

- name: Remove any undesired artifacts from build
  include: clean_image.yml
