---
- include: ../../init/main.yml

- include: ../../common/openshift-cluster/redeploy-certificates/nodes-backup.yml

- include: ../../common/openshift-node/certificates.yml
  vars:
    openshift_certificates_redeploy: true

- include: ../../common/openshift-node/restart.yml
