---
- name: Package Manager | Init the did_install fact
  set_fact:
    did_install: false

- include: pkgMgrInstallers/centos-install.yml
  when: (ansible_os_family == "RedHat") and
        not is_atomic

- name: Package Manager | Set fact saying we did CentOS package install
  set_fact:
    did_install: true
  when: (ansible_os_family == "RedHat")
