# -*- mode: ruby -*-
# vi: set ft=ruby :


# all config options can be found at: https://github.com/vagrant-libvirt/vagrant-libvirt#installation
Vagrant.configure("2") do |config|
  config.vm.box = "centos7libvirt"
  config.vm.provider :libvirt do |libvirt|
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end

  config.vm.define :master do |master|
    master.vm.hostname = master1.vialis.local
    master.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
      domain.machine_virtual_size = 20
    end
    master.vm.provision :ansible do |ansible|
        # Disable default limit to connect to all the machines
        ansible.force_remote_user = false
        ansible.inventory_path = "ansible-hosts.cfg"
        ansible.limit = "all"
        ansible.playbook = "openshift-ansible/playbooks/byo/config.yml"
      end
  end

  config.vm.define :node1 do |node1|
    node1.vm.hostname = node1.vialis.local
    node1.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
      domain.machine_virtual_size = 25
    end
  end



end
