# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


# all config options can be found at: https://github.com/vagrant-libvirt/vagrant-libvirt#installation
$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
git clone https://github.com/openshift/openshift-ansible.git /home/vagrant/openshift-ansible
chown vagrant /home/vagrant/openshift-ansible
sudo mv /etc/ansible/hosts /etc/ansible/hosts.bak
sudo cp /vagrant/ansible-hosts.cfg /etc/ansible/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos7qemu"
  config.vm.provision "shell", inline: $script
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end

  config.vm.define :master1 do |master|
    master.vm.hostname = "master.vialis.local"
    master.vm.provider :libvirt do |domain|
      domain.memory = 8192
      domain.cpus = 2
      domain.machine_virtual_size = 50
    end
    master.vm.provision :ansible_local do |ansible|
        # Disable default limit to connect to all the machines
        #ansible.inventory_path = "/vagrant/ansible-hosts.cfg"
        ansible.verbose = true
        ansible.limit = "master1"
        ansible.become_user = "root"
        ansible.become = true
        ansible.playbook = "/home/vagrant/openshift-ansible/playbooks/byo/config.yml"
        #ansible.groups = {
        #  "masters" => ["master1"],
        #  "nodes"   => ["node1"]
        #}
      end
  end

  config.vm.define :node1 do |node|
    node.vm.hostname = "node1.vialis.local"
    node.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.machine_virtual_size = 50
    end
    node.vm.provision :ansible_local do |ansible|
        # Disable default limit to connect to all the machines
        #ansible.inventory_path = "/vagrant/ansible-hosts.cfg"
        ansible.verbose = true
        ansible.limit = "node1"
        ansible.become_user = "root"
        ansible.become = true
        ansible.playbook = "/home/vagrant/openshift-ansible/playbooks/byo/config.yml"
        #ansible.groups = {
        #  "masters" => ["master1"],
        #  "nodes"   => ["node1"]
        #}
      end
  end



end
