---
- name: Ensure all cloud resources necessary for the cluster, including instances, have been started
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: provision a GCP cluster in the specified project
    include_role:
      name: openshift_gcp

- name: run the init
  include: ../../init/main.yml

- name: run the config
  include: ../../common/openshift-cluster/config.yml
