---
- name: Hosted Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Hosted install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_hosted:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- include: create_persistent_volumes.yml

- include: openshift_default_storage_class.yml

- include: openshift_hosted_create_projects.yml

- include: openshift_hosted_router.yml

- include: openshift_hosted_registry.yml

- include: cockpit-ui.yml

- include: openshift_prometheus.yml
  when: openshift_hosted_prometheus_deploy | default(False) | bool

- include: install_docker_gc.yml
  when:
  - openshift_use_crio | default(False) | bool
  - openshift_crio_enable_docker_gc | default(False) | bool

- name: Hosted Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Hosted install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_hosted:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
