---
- include: ../init/evaluate_groups.yml

- name: Subscribe hosts, update repos and update OS packages
  hosts: oo_all_hosts
  roles:
  - role: rhel_subscribe
    when:
    - deployment_type == 'openshift-enterprise'
    - ansible_distribution == "RedHat"
    - lookup('env', 'rhel_skip_subscription') | default(rhsub_skip, True) | default('no', True) | lower in ['no', 'false']
  - role: openshift_repos
  - role: os_update_latest
