---
- include: ../../init/evaluate_groups.yml

- name: Ensure there are new_masters or new_nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - fail:
      msg: >
        Detected no new_masters or no new_nodes in inventory. Please
        add hosts to the new_masters and new_nodes host groups to add
        masters.
    when:
    - g_new_master_hosts | default([]) | length == 0
    - g_new_node_hosts | default([]) | length == 0

# Need a better way to do the above check for node without
# running evaluate_groups and init/main.yml
- include: ../../init/main.yml

- include: ../../common/openshift-master/scaleup.yml
