---
- name: Set ETCD_FORCE_NEW_CLUSTER=true on first etcd host
  lineinfile:
    line: "ETCD_FORCE_NEW_CLUSTER=true"
    dest: /etc/etcd/etcd.conf
    backup: true

- name: Start etcd
  systemd:
    name: "{{ etcd_service }}"
    state: started

- name: Wait for cluster to become healthy after bringing up first member
  command: >
    etcdctl --cert-file {{ etcd_peer_cert_file }} --key-file {{ etcd_peer_key_file }} --ca-file {{ etcd_peer_ca_file }} --endpoint https://{{ etcd_peer }}:{{ etcd_client_port }} cluster-health
  register: l_etcd_migrate_health
  until: l_etcd_migrate_health.rc == 0
  retries: 3
  delay: 30

- name: Unset ETCD_FORCE_NEW_CLUSTER=true on first etcd host
  lineinfile:
    line: "ETCD_FORCE_NEW_CLUSTER=true"
    dest: /etc/etcd/etcd.conf
    state: absent
    backup: true

- name: Restart first etcd host
  systemd:
    name: "{{ etcd_service }}"
    state: restarted
