---
- yedit:
    src: "{{ openshift.common.config_base }}/master/master-config.yaml"
    key: 'etcdClientInfo.urls'
    value: "{{ openshift.master.etcd_urls }}"
  notify:
  - restart master api
  - restart master controllers
