---
# This file exists because we call systemd_units.yml from outside of the role
# during upgrades.  When we remove this pattern, we can probably
# eliminate most of these set_fact items.

- name: Set openshift_master_config_dir if unset
  set_fact:
    openshift_master_config_dir: '/etc/origin/master'
  when: openshift_master_config_dir is not defined

- name: Set r_openshift_master_data_dir if unset
  set_fact:
    r_openshift_master_data_dir: "{{ openshift_data_dir | default('/var/lib/origin') }}"
  when: r_openshift_master_data_dir is not defined

- set_fact:
    oreg_auth_credentials_path: "{{ r_openshift_master_data_dir }}/.docker"
  when: oreg_auth_credentials_path is not defined

- set_fact:
    oreg_host: "{{ oreg_url.split('/')[0] if (oreg_url is defined and '.' in oreg_url.split('/')[0]) else '' }}"
  when: oreg_host is not defined

- set_fact:
    oreg_auth_credentials_replace: False
  when: oreg_auth_credentials_replace is not defined

- name: Set openshift_master_debug_level
  set_fact:
    openshift_master_debug_level: "{{ debug_level | default(2) }}"
  when:
  - openshift_master_debug_level is not defined

- name: Init HA Service Info
  set_fact:
    containerized_svc_dir: "{{ containerized_svc_dir | default('/usr/lib/systemd/system') }}"
    ha_svc_template_path: "{{ ha_svc_template_path | default('native-cluster') }}"
