---
# GCE instances are starting with xfs AND barrier=1, which is only for extfs.
- name: Remove barrier=1 from XFS fstab entries
  lineinfile:
    path: /etc/fstab
    regexp: '^(.+)xfs(.+?),?barrier=1,?(.*?)$'
    line: '\1xfs\2 \4'
    backrefs: yes

- name: Ensure the root filesystem has XFS group quota turned on
  lineinfile:
    path: /boot/grub2/grub.cfg
    regexp: '^(.*)linux16 (.*)$'
    line: '\1linux16 \2 rootflags=gquota'
    backrefs: yes

- name: Ensure the root partition grows on startup
  copy: src=partition.conf dest=/etc/systemd/system/google-instance-setup.service.d/
