---
- include: ../../common/openshift-cluster/openshift_hosted.yml

- include: ../../common/openshift-cluster/openshift_metrics.yml
  when: openshift_metrics_install_metrics | default(false) | bool

- include: ../../common/openshift-cluster/openshift_logging.yml
  when: openshift_logging_install_logging | default(false) | bool

- include: ../../common/openshift-cluster/service_catalog.yml
  when: openshift_enable_service_catalog | default(false) | bool

- include: ../../common/openshift-management/config.yml
  when: openshift_management_install_management | default(false) | bool

- name: Print deprecated variable warning message if necessary
  hosts: oo_first_master
  gather_facts: no
  tasks:
  - debug: msg="{{__deprecation_message}}"
    when:
    - __deprecation_message | default ('') | length > 0
