---
- name: Setup the master node group
  hosts: localhost
  tasks:
  - include_role:
      name: openshift_aws
      tasks_from: setup_master_group.yml

- name: set the master facts for hostname to elb
  hosts: masters
  gather_facts: no
  remote_user: root
  tasks:
  - include_role:
      name: openshift_aws
      tasks_from: master_facts.yml

- name: run the init
  include: ../../init/main.yml

- name: perform the installer openshift-checks
  include: ../../common/openshift-checks/install.yml

- name: etcd install
  include: ../../common/openshift-etcd/config.yml

- name: include nfs
  include: ../../common/openshift-nfs/config.yml
  when: groups.oo_nfs_to_config | default([]) | count > 0

- name: include loadbalancer
  include: ../../common/openshift-loadbalancer/config.yml
  when: groups.oo_lb_to_config | default([]) | count > 0

- name: include openshift-master config
  include: ../../common/openshift-master/config.yml

- name: include master additional config
  include: ../../common/openshift-master/additional_config.yml

- name: include master additional config
  include: ../../common/openshift-node/config.yml

- name: include openshift-glusterfs
  include: ../../common/openshift-glusterfs/config.yml
  when: groups.oo_glusterfs_to_config | default([]) | count > 0
