---
# Once an AMI is built then this script is used for
# the one stop shop to provision and install a cluster
# this playbook is run with the following parameters:
# ansible-playbook -i openshift-ansible-inventory provision_install.yml
- name: Include the provision.yml playbook to create cluster
  include: provision.yml

- name: Include the install.yml playbook to install cluster on masters
  include: install.yml

- name: provision the infra/compute playbook to install node resources
  include: provision_nodes.yml

- name: Include the accept.yml playbook to accept nodes into the cluster
  include: accept.yml

- name: Include the hosted.yml playbook to finish the hosted configuration
  include: hosted.yml
