---
- name: Backup master etcd certificates
  shell: >
    tar -czvf /etc/origin/master/master-etcd-certificate-backup-{{ ansible_date_time.epoch }}.tgz
    /etc/origin/master/master.etcd-*
  args:
    warn: no
